
CREATE DATABASE MANTENIMIENTO
GO 
USE MANTENIMIENTO
GO 

CREATE TABLE USUARIO
(
	id int identity,
	nombre varchar(50) not null,
	correoelectronico varchar(50),
	telefono varchar(15),
	CONSTRAINT uq_telefono UNIQUE(telefono),
	CONSTRAINT pk_idusuario PRIMARY KEY(id)
)
GO

CREATE TABLE TECNICO
(
	id int identity,
	nombre varchar(50),
	especialidad varchar(50),
	CONSTRAINT pk_idtecnico PRIMARY KEY (id)
)
GO

CREATE TABLE EQUIPO
(
	id int identity,
	tipoequipo varchar(50) not null,
	modelo varchar(50),
	CONSTRAINT pk_idequipo PRIMARY KEY (id),
	idusuario int CONSTRAINT fk_idusuario FOREIGN KEY(idusuario) REFERENCES USUARIO(id)
)
GO

CREATE TABLE REPARACION
(
	id int identity,
	fechasolicitud datetime,
	estado char(1),
	CONSTRAINT pk_idreparacion PRIMARY KEY (id),
	idequipo int CONSTRAINT fk_idequipo FOREIGN KEY(idequipo) REFERENCES EQUIPO(id)
)
GO

CREATE TABLE DETALLEREPARACION
(
	id int identity,
	descripcion varchar(50),
	fechainicio datetime,
	fechafin datetime,
	CONSTRAINT pk_iddetallereparacion PRIMARY KEY (id),
	idreparacion int CONSTRAINT fk_idreparacion FOREIGN KEY(idreparacion) REFERENCES REPARACION(id)
)
GO

CREATE TABLE ASIGNACION
(
	id int identity,
	fechaasignacion datetime,
	CONSTRAINT pk_idasignacion PRIMARY KEY (id),
	idtecnico int CONSTRAINT fk_idtecnico FOREIGN KEY(idtecnico) REFERENCES TECNICO(id)
)
GO

CREATE TABLE USUARIOLOGIN
(
  CORREO VARCHAR (50),
  CLAVE VARCHAR (50)
)
GO


--Procedimientos almacenados Tabla USUARIOS--

CREATE PROCEDURE CONSULTARUSUARIO
AS
	BEGIN
		SELECT * FROM USUARIO
	END


CREATE PROCEDURE BORRARUSUARIO
@CODIGO INT 
AS
	BEGIN
		DELETE USUARIO WHERE ID=@CODIGO
	END


CREATE PROCEDURE CONSULTARUSUARIO_FILTRO
@CODIGO INT 
AS
	BEGIN
		SELECT * FROM USUARIO WHERE ID = @CODIGO
	END


CREATE PROCEDURE ACTUALIZARUSUARIO
@CODIGO INT,
@NOMBRE VARCHAR(50),
@CORREOELECTRONICO VARCHAR(50),
@TELEFONO VARCHAR(15)
AS
	BEGIN
		UPDATE USUARIO SET NOMBRE = @NOMBRE, CORREOELECTRONICO = @CORREOELECTRONICO, TELEFONO = @TELEFONO WHERE ID=@CODIGO
	END 


CREATE PROCEDURE INGRESARUSUARIO
@NOMBRE VARCHAR(50),
@CORREOELECTRONICO VARCHAR(50),
@TELEFONO VARCHAR(15)
AS
	BEGIN
		INSERT INTO USUARIO (NOMBRE,CORREOELECTRONICO,TELEFONO ) VALUES(@NOMBRE,@CORREOELECTRONICO,@TELEFONO)
	END


---Procedimientos almacenados Tabla TECNICOS--

CREATE PROCEDURE CONSULTARTECNICO
AS
	BEGIN
		SELECT * FROM TECNICO
	END


CREATE PROCEDURE BORRARTECNICO
@CODIGO INT 
AS
	BEGIN
		DELETE TECNICO WHERE ID=@CODIGO
	END


CREATE PROCEDURE CONSULTARTECNICO_FILTRO
@CODIGO INT 
AS
	BEGIN
		SELECT * FROM TECNICO WHERE ID = @CODIGO
	END


CREATE PROCEDURE ACTUALIZARTECNICO
@CODIGO INT,
@NOMBRE VARCHAR(50),
@ESPECIALIDAD VARCHAR(50)

AS
	BEGIN
		UPDATE TECNICO SET NOMBRE = @NOMBRE, ESPECIALIDAD = @ESPECIALIDAD WHERE ID=@CODIGO
	END 


CREATE PROCEDURE INGRESARTECNICO
@CODIGO INT,
@NOMBRE VARCHAR(50),
@ESPECIALIDAD VARCHAR(50)
AS
	BEGIN
		INSERT INTO TECNICO (NOMBRE,ESPECIALIDAD) VALUES(@NOMBRE,@ESPECIALIDAD)
	END


---Procedimientos almacenados Tabla EQUIPOS---

CREATE PROCEDURE CONSULTAREQUIPO
AS
	BEGIN
		SELECT * FROM EQUIPO
	END


CREATE PROCEDURE BORRAREQUIPO
@CODIGO INT 
AS
	BEGIN
		DELETE EQUIPO WHERE ID=@CODIGO
	END



CREATE PROCEDURE CONSULTAREQUIPO_FILTRO
@CODIGO INT 
AS
	BEGIN
		SELECT * FROM EQUIPO WHERE ID = @CODIGO
	END


CREATE PROCEDURE ACTUALIZAREQUIPO
@CODIGO INT,
@TIPOEQUIPO VARCHAR(50),
@MODELO VARCHAR(50)

AS
	BEGIN
		UPDATE EQUIPO SET  TIPOEQUIPO  = @TIPOEQUIPO, MODELO = @MODELO WHERE ID=@CODIGO
	END 



CREATE PROCEDURE INGRESAREQUIPO
@CODIGO INT,
@TIPOEQUIPO VARCHAR(50),
@MODELO VARCHAR(50)
AS
	BEGIN
		INSERT INTO EQUIPO (TIPOEQUIPO,MODELO) VALUES(@TIPOEQUIPO,@MODELO)
	END




CREATE PROCEDURE VALIDARUSUARIOLOGIN
@correo VARCHAR(50),
@clave VARCHAR(50)
AS
	BEGIN
		SELECT correo, clave FROM USUARIOLOGIN WHERE correo = @correo and clave = @clave
	END

	EXEC VALIDARUSUARIOLOGIN 'javi89@gmail.com', '1234'